# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(977812bc-0cfb-4c57-8912-a7804ccf8fba)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials --resource-group myResourceGroup --name myAKSCluster'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f **/*deployment.yml
      kubectl apply -f **/*service.yml
    workingDirectory: '$(system.defaultworkingdirectory)'